@hostname = localhost
@port = 7000
@host = {{hostname}}:{{port}}
@contentType = application/json


### Ping redis
GET http://{{host}}/ping HTTP/1.1

### write open port to db
POST http://{{host}}/write HTTP/1.1
Content-Type: "application/json"

[
    {
        "Host": "192.168.2.123",
        "Port": 2331,
        "Protocol": "http"
    }
]

### test address exits
# http://192.168.2.237:80
HEAD http://{{host}}/redis
    ?protocol=http&host=192.168.2.123&port=4000



# {"Host":"192.168.2.233","Port":233,"Protocol":"http"}

### get record count
GET http://{{host}}/tester 

### post batch to get db message
POST http://{{host}}/tester  HTTP/1.1
Content-Type: "application/json"

{
    "cursor": 0,
    "match": "",
    "count": 10
}

### decrease score
DELETE http://{{host}}/tester  HTTP/1.1
Content-Type: "application/json"

{
    "Host": "192.168.2.1",
    "Port": 80,
    "Protocol": "http"
}


### update score to max
PUT http://{{host}}/tester HTTP/1.1
Content-Type: "application/json"

{
    "Host": "192.168.2.1",
    "Port": 80,
    "Protocol": "http"
}
