@hostname = localhost
@port = 7795
@host = {{hostname}}:{{port}}
@contentType = application/json

### send get to start common scan
GET http://{{host}}/start HTTP/1.1


### Send post to star scan
POST http://{{host}}/start HTTP/1.1
Content-Type: {{contentType}}

{
    "Protocol": "http",
    "Host": "farmer233.top",
    "Start": 1,
    "End": 8080,
    "Timeout": 5,
    "SSL": false
}

### fast discover
HEAD http://{{host}}/start HTTP/1.1


### random host
GET http://{{host}}/randome HTTP/1.1

### segment, segment 的内容将拼接在x -> 172.16.x.[1-255]
POST http://{{host}}/segment HTTP/1.1
Content-Type: {{contentType}}

{
    "segment": 1 
}
