### send get to start common scan
GET http://localhost:6500/start HTTP/1.1


### Send post to star scan
POST http://localhost:6500/start HTTP/1.1
Content-Type: "application/json"

{
    "Protocol": "http",
    "Host": "xiaotao233.top",
    "Start": 1,
    "End": 65535,
    "Timeout": 5,
    "SSL": false
}

# content